select * from customers
select * from geolocation
select * from sellers
select * from order_reviews
select * from order_payments
select * from order_items
select * from orders
select * from products
select * from product_category_name_translation
-----------
--1. What is the total revenue generated by Olist, and how has it changed over time?
select ROUND(sum(payment_value),2) AS TotalRevenue 
from order_payments op
join orders o on op.order_id = o.order_id
where o.order_status = 'delivered'
-- Monthly revenue by year and month
select ROUND(sum(payment_value),2) AS MonthlyRevenue, 
YEAR(order_purchase_timestamp) AS [Year], Month(order_purchase_timestamp) AS [Month]
from order_payments op
JOIN orders o on op.order_id = o.order_id
WHERE o.order_status = 'delivered'
group by 
    YEAR(o.order_purchase_timestamp), 
    MONTH(o.order_purchase_timestamp)
ORDER BY [Year], [Month];
--------------------------------------------------------------------------------------------
--2. How many orders were placed on Olist, and how does this vary by month or season?
-- Monthly number of orders
select COUNT(order_id) AS '# of orders', 
YEAR(order_purchase_timestamp) AS [Year], MONTH(order_purchase_timestamp) AS [Month]
from orders
WHERE order_status = 'delivered'
group by YEAR(order_purchase_timestamp), MONTH(order_purchase_timestamp)
order by [Year], [Month]
-- seasonality number of orders
select COUNT(order_id) AS '# of orders',
YEAR(order_purchase_timestamp) AS [Year], DATEPART(QUARTER, order_purchase_timestamp) AS [Quarter]
from orders
WHERE order_status = 'delivered'
group by YEAR(order_purchase_timestamp), DATEPART(QUARTER, order_purchase_timestamp)
order by [Year], [Quarter]
--------------------------------------------------------------------------------------------
--3. What are the most popular product categories on Olist, and how do their sales volumes compare to each other?
select product_category_name_english, COUNT(O.order_id) as '# of orders', ROUND(SUM(payment_value),2) AS total_revenue
from order_items O
JOIN order_payments D on O.order_id = D.order_id
JOIN products P on o.product_id = p.product_id
JOIN product_category_name_translation C on p.product_category_name = C.product_category_name
group by product_category_name_english
order by COUNT(O.order_id) desc
--------------------------------------------------------------------------------------------
--4. What is the average order value (AOV) on Olist, and how does this vary by product category or payment method?
--By Product Category
select PT.product_category_name_english, (SUM(OP.payment_value) / COUNT(OP.order_id)) AS AOV_by_Category
from products P
JOIN product_category_name_translation PT on PT.product_category_name = P.product_category_name
JOIN order_items OI on OI.product_id = P.product_id
JOIN order_payments OP on OP.order_id = OI.order_id
group by PT.product_category_name_english
order by AOV_by_Category desc
--By Payment Method
select payment_type, (SUM(payment_value) / COUNT(order_id)) AS AOV_by_payment_method
from order_payments
group by payment_type
order by AOV_by_payment_method desc
--------------------------------------------------------------------------------------------
--5. How many sellers are active on Olist, and how does this number change over time?
--seller is active is if they were able to successfully deliver an item to the customer 
--and the order should have been made within the last 30 days from the most recent order purchase date.
select * from orders
select * from sellers
select * from order_items
-------
With cte as(
select S.seller_id, R.order_status, R.order_purchase_timestamp
from order_items OI
JOIN orders R on OI.order_id = R.order_id
JOIN sellers S ON OI.seller_id = S.seller_id
group by S.seller_id, R.order_status, R.order_purchase_timestamp
HAVING R.order_status = 'delivered' AND (DAY(R.order_purchase_timestamp) - max(DAY(R.order_purchase_timestamp)))<=30
)
select COUNT(distinct seller_id) AS active_sellers
from cte
--------------------------------------------------------------------------------------------
--6. How many customers have made repeat purchases on Olist?
with cte as(
select C.customer_unique_id, COUNT(distinct O.order_id) AS '# of orders'
from customers C
JOIN orders O on C.customer_id = O.customer_id
group by C.customer_unique_id
HAVING COUNT(distinct O.order_id)>1
)
select COUNT(*) AS '# of repeat purchase' from cte
--------------------------------------------------------------------------------------------
--7. What is the average customer rating for products sold on Olist, and how does this impact sales performance?
select PT.product_category_name_english, AVG(review_score) AS avg_score, SUM(payment_value) AS revenue, AVG(payment_value) as avg_revenue
from order_reviews R
JOIN orders O on R.order_id = O.order_id
JOIN order_payments OP on OP.order_id = R.order_id
JOIN order_items OI on OI.order_id = OP.order_id
JOIN products P on OI.product_id = P.product_id
JOIN product_category_name_translation PT on P.product_category_name = PT.product_category_name
where O.order_status!='canceled' and O.order_approved_at IS NOT NULL 
group by PT.product_category_name_english
order by avg_score
--------------------------------------------------------------------------------------------
--8. What is the average order cancellation rate on Olist?
SELECT 
    CAST(COUNT(order_id) AS FLOAT) * 100 / 
    (SELECT COUNT(order_id) FROM orders) AS cancellation_rate_percent
FROM orders
WHERE order_status = 'canceled';
--------------------------------------------------------------------------------------------
--9. What are the top-selling products on Olist?
SELECT P.product_id, PT.product_category_name_english, COUNT(*) AS total_sold
FROM order_items OI
JOIN products P ON OI.product_id = P.product_id
LEFT JOIN product_category_name_translation PT ON P.product_category_name = PT.product_category_name
GROUP BY P.product_id, PT.product_category_name_english
ORDER BY total_sold DESC;
--------------------------------------------------------------------------------------------
--10. Which payment methods are most commonly used by Olist customers, and how does this vary by product category or geographic region?
select payment_type, COUNT(payment_type)  AS usage_count 
from order_payments
group by payment_type
order by COUNT(payment_type) desc
--by geographic region
SELECT C.customer_state, COUNT(*) AS NO_ORDERS, OP.payment_type
FROM order_payments OP
JOIN orders O ON OP.order_id = O.order_id
JOIN customers C ON C.customer_id = O.customer_id
GROUP BY C.customer_state, OP.payment_type
ORDER BY NO_ORDERS DESC;
--------------------------------------------------------------------------------------------
--11. Which product categories have the highest profit margins on Olist?
select product_category_name_english, (SUM(payment_value) - SUM(price) + SUM(freight_value)) / SUM(payment_value) * 100 AS profit_margin
from order_payments OP
JOIN order_items OI on OP.order_id = OI.order_id
JOIN products P on P.product_id = OI.product_id
JOIN product_category_name_translation PT on PT.product_category_name = P.product_category_name
group by product_category_name_english
order by profit_margin desc